# Project information
site_name: Documentación de Usuario.
site_dir: ../../../public/docs/user_budget
use_directory_urls: true

# Page tree
nav:
      - Inicio: index.md
      - Módulo de Presupuesto:
        - Clasificador Presupuestario: accounts.md
        - Formulación: subspecific_formulations.md
        - Modificaciones: modifications.md
        - Ejecución: execution.md
        - Reportes: reports.md
      - Configuración: 
        - Formatos de Códigos: setting/code_format.md 
        - Proyectos: setting/projects.md 
        - Acciones Centralizadas: setting/centralized_actions.md
        - Acciones Específicas: setting/specific_actions.md
      - Preguntas Frecuentes: frequent_questions.md  

# Repository
repo_name: Repositorio-Kavac
repo_url: https://gestion.cenditel.gob.ve/trac/browser/kavac/

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: es
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    # primary: light-blue
    accent: light-blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png
  icon: 
    repo: fontawesome/brands/git-square 
  
          
# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - with-pdf:
      author: Luis Ramírez
      copyright: http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
      cover_subtitle: KAVAC - Módulo de Presupuesto
      output_path: ../../../public/docs/user_budget_module_manual.pdf

# Customization
# extra:
#   social:
#     - icon: 
#       link: 

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details

# css additional
extra_css:
  - stylesheets/extra.css












            

