# Project information
site_name: Documentación de Usuario.
site_dir: ../public/docs/user
use_directory_urls: true

# Page tree
nav:
      - Inicio: index.md
      - Sistema KAVAC:
        - Acerca de: about.md
        - Gestión de Proyecto: development_methodology.md
        - Información General: information.md
        - Instalación: installation.md
      - Primeros Pasos : 
        - Inicio de Sesión: getting_started/login.md
        - Recuperar Contraseña: getting_started/reset_password.md
        - Cambiar Contraseña: getting_started/change_password.md
        - Configurar Cuenta de Usuario: getting_started/user_account_setting.md
        - Configurar Organización: getting_started/organization_setup.md
      - Configuración:
        - Configuración del Sistema: setting/setting.md
        - Configuración General: setting/general_setting.md
        - Configuración de Acceso: setting/access_setting.md
        - Configuración de Módulos: setting/modules_setting.md
      - Panel de Control:
        - Panel de Control: control_panel/control_panel.md
        - Herramientas para Desarrolladores: control_panel/developer_tools.md
        - Control de Acceso: control_panel/access_control.md
        - Módulo de Contabilidad: control_panel/accounting_module.md
        - Módulo de Bienes: control_panel/asset_module.md
        - Módulo de Almacén: control_panel/warehouse_module.md
      - Preguntas Frecuentes: frequent_questions.md

# Repository
repo_name: Repositorio-Kavac
repo_url: https://gestion.cenditel.gob.ve/trac/browser/kavac/

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: es
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    # primary: light-blue
    accent: light-blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png
  icon:
    repo: fontawesome/brands/git-square


# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - with-pdf:
      author: Luis Ramírez
      copyright: http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
      cover_subtitle: KAVAC - ERP para la gestión organizacional
      output_path: ../../../public/docs/user_base_manual.pdf

# Customization
# extra:
#   social:
#     - icon:
#       link:

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details

# css additional
extra_css:
  - stylesheets/extra.css










