# Project information
site_name: Documentación de Usuario.
site_dir: ../../../public/docs/user_warehouse
use_directory_urls: true

# Page tree
nav:
      - Inicio: index.md
      - Módulo de Almacén:
        - Recepciones de Almacén: receptions.md
        - Solicitudes de Almacén: requests.md
        - Movimientos de Almacén: movements.md
        - Reportes: 
          - Inventario de productos: inventory.md
          - Solicitudes de productos: request_report.md
          - Stocks mínimo y máximo: stocks.md
      - Configuración: 
        - Formatos de Códigos: setting/code_format.md
        - Parámetros Generales: setting/general_parameters.md
        - Configuración General: setting/general_setting.md
      - Preguntas Frecuentes: frequent_questions.md
       
      
# Repository
repo_name: Repositorio-Kavac
repo_url: https://gestion.cenditel.gob.ve/trac/browser/kavac/

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: es
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    # primary: light-blue
    accent: light-blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png
  icon: 
    repo: fontawesome/brands/git-square 
  
          
# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - with-pdf:
      author: CENDITEL Nodo Mérida
      copyright: http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
      cover_subtitle: KAVAC - Módulo de Almacén
     #output_path: ../../../public/docs/user_warehouse_module_manual.pdf

# Customization
# extra:
#   social:
#     - icon: 
#       link: 

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details

# css additional
extra_css:
  - stylesheets/extra.css

    








            

